version: '2'
services:
    iniduscloudplatform-app:
        image: iniduscloudplatform
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://iniduscloudplatform-mariadb:3306/iniduscloudplatform
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=iniduscloudplatform-elasticsearch:9300
            - SPRING_RABBITMQ_HOST=iniduscloudplatform-rabbitmq
            - ***REMOVED***
            - ***REMOVED***
            - ***REMOVED***
            - ***REMOVED***

        ports:
            - 8181:9582
    iniduscloudplatform-mariadb:
        extends:
            file: mariadb.yml
            service: iniduscloudplatform-mariadb
    iniduscloudplatform-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: iniduscloudplatform-elasticsearch
    iniduscloudplatform-rabbitmq:
        extends:
            file: rabbitmq.yml
            service: iniduscloudplatform-rabbitmq
