version: '2'
services:
    iniduscloudplatform-app:
        image: "iniduscloudplatform"
        env_file:
          - .env
          - iniduscloudplatform-variables.env
        ports:
            - 8080:9582

    iniduscloudplatform-mariadb:
        extends:
            file: mariadb.yml
            service: iniduscloudplatform-mariadb
        env_file:
          - .env
          - iniduscloudplatform-variables.env

    iniduscloudplatform-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: iniduscloudplatform-elasticsearch
        env_file:
          - .env
          - iniduscloudplatform-variables.env

    iniduscloudplatform-rabbitmq:
        extends:
            file: rabbitmq.yml
            service: iniduscloudplatform-rabbitmq
        env_file:
          - .env
          - iniduscloudplatform-variables.env
