version: '2'
services:
    iniduscloudplatform-mariadb:
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/iniduscloudplatform/mysql/:/var/lib/mysql/
        env_file:
          - iniduscloudplatform-variables.env
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
